highlighter: pygments
permalink: /blog/:categories/:year/:month/:day/:title.html
# Site settings
title: "rkappa по-русски"
email: lptolik@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  rkappa это пакет для работы с шаблонами моделей на языке kappa
  в среде моделирования R/Bioconductor. Основной целью этого пакета
  является идентификация параметров, многомерный разведочный анализ
  поведения моделей и анализ их параметрической чувствительности. 
twitter_username: lptolik
github_username:  lptolik
#baseurl: "/ru" # the subpath of your site, e.g. /blog/
#url: "http://lptolik.github.io/R4Kappa" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
